---
title: "Talking Data Hybrid Sampling Using SMOTE"
author: "Jesse Weiss"
date: "April 11, 2018"
output: html_document
---
<style>
body{
background: white;
}
#header {
    margin: auto;
    width: 50%;
    text-align: center;}
h1 {
font-size:26px !important;
}
.li_1 {
padding-bottom: 10px;
}
</style>

```{r setup, include=TRUE}
library(data.table)
library(dplyr)
library(tidyr)
library(caret)
library(DMwR)
library(ROCR)
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
train_all <- fread('train_all.csv', stringsAsFactors = F)

# change is_attributed & original vars to factors
train_all <- train_all %>% 
  mutate(is_attributed = factor(is_attributed),
         channel = factor(channel),
         os = factor(os),
         device = factor(device),
         app = factor(app),
         ip = factor(ip),
         click_time = factor(click_time))

train1 <- train_all[1:1000000,]
test1 <- train_all[1000001:1500000,]

table(train1$is_attributed)
```

```{r}
set.seed(100)
smote_train <- SMOTE(is_attributed ~ ., data = train1, perc.over = 1000)

table(smote_train$is_attributed)
```

```{r}
#Test with Logistic Regression using 10s predictors
mod1 <- glm(is_attributed ~ channelIp10s + channelApp10s + channelDevice10s + channelOs10s + 
              osIp10s + osApp10s + osDevice10s + appAttrib + deviceAttrib + osAttrib + channelAttrib +
              ip10s + app10s + device10s + os10s + channel10s, data = smote_train, family = 'binomial')

mod1.prob <- predict(mod1, newdata = test1, type = 'response')
mod1.predict <- ifelse(mod1.prob > .5, 1,0)
table(test1$is_attributed,mod1.predict)
```

```{r}
rocr_pred <- prediction(mod1.prob, test1$is_attributed)
rocr_perf <- performance(rocr_pred, "tpr", "fpr")
performance(rocr_pred,measure='auc')

roc_df <- data.frame(fp_rate = rocr_perf@x.values[[1]], tp_rate = rocr_perf@y.values[[1]])
roc_df %>% 
  ggplot(aes(x=fp_rate,y=tp_rate))+
  geom_line(color='green3', size=1)+
  stat_function(fun = function(x) x)+
  theme_bw()
```